version: '3.8'

services:

  php-apache-portfolio:
    build:
      context: ./.docker/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html

volumes:
  php-apache-portfolio: